services:
  - type: web
    name: quickbuthealthy-backend
    env: python
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 server.app:app"
    plan: free
